IF EXISTS (SELECT * FROM SYS.PROCEDURES WHERE NAME = 'USP_DEL_USER_DADOS_PESSOAIS')
BEGIN
	DROP PROC USP_DEL_USER_DADOS_PESSOAIS
END
GO

CREATE PROC USP_DEL_USER_DADOS_PESSOAIS
	 @id INT  = NULL
AS
BEGIN
	IF @id IS NOT NULL
	BEGIN
		DELETE FROM 
			TB_USER_DADOS_PESSOAIS
		WHERE 
			ID = COALESCE(@id,ID)
	END 
END
GO