IF NOT EXISTS(SELECT * FROM SYS.tables WHERE name = 'TB_ADM')
BEGIN
	CREATE TABLE TB_ADM
	(
		 ID INT PRIMARY KEY IDENTITY
		,NOME VARCHAR(100) NOT NULL
		,EMAIL VARCHAR(300) NOT NULL
		,SENHA VARCHAR(100) NOT NULL
	)
END
GO