IF NOT EXISTS(SELECT * FROM SYS.tables WHERE name = 'TB_ADM')
BEGIN
	CREATE TABLE TB_USER_DADOS_PESSOAIS
	(
		 ID INT PRIMARY KEY IDENTITY
		,Nome VARCHAR(100) NOT NULL
		,Email VARCHAR(300) NOT NULL
		,Senha VARCHAR(100) NOT NULL
		,Telefone VARCHAR(20) NULL
		,Celular VARCHAR(20) NULL
		,DataNascimento VARCHAR(10) NOT NULL 
	)
END
GO
